### ISSUE TITLE
sql-generator or format function ?

### ISSUE THREAD

**Issue by victor0801x** [MariaDB/mariadb-connector-nodejs#14]
any chance to expose sql-generator function, as same as `mysql.format` (or sqlstring)

**Comment by rusher** [comment]
@victor0801x 
maybe, if you can explain some use case, that would help. I don't see one for the moment (I may be totally wrong), but easily see the problem of injection that can cause to leave query construction to applications.

What cannot be achived using question mark ? (like 'INSERT INTO myTable (col1, col2) VALUE (?,?)' )

**Comment by victor0801x** [comment]
I know that are some security problem,
currently, in our server-side application
1. log the none-private or none-sensitive sqlstring in our log for debug use
2. peek, quick-check or verify the sqlstring before real-query 
3. recovery the data from query log for some accidents or query error

**Comment by rusher** [comment]
Error format are quite different from npm mysql/mysql2. Query is contain in it. 
like : 
```
{ Error: (conn=10965, no: 1146, SQLState: 42S02) Table 'testn.falsetable' doesn't exist
sql: INSERT INTO falseTable(t1, t2, t3, t4, t5) values (?, ?, ?, ?, ?)  - parameters:[1,0x01ff,'hh','01/01/2001 00:00:00.000',null]
    at Object.module.exports.createError (C:\projects\mariadb\mariadb-connector-nodejs-5\lib\misc\errors.js:55:10)
    at Query.throwError (C:\projects\mariadb\mariadb-connector-nodejs-5\lib\cmd\command.js:33:20)
    at Query.readResponsePacket (C:\projects\mariadb\mariadb-connector-nodejs-5\lib\cmd\resultset.js:51:21)
    at PacketInputStream.receivePacket (C:\projects\mariadb\mariadb-connector-nodejs-5\lib\io\packet-input-stream.js:51:9)
    at PacketInputStream.onData (C:\projects\mariadb\mariadb-connector-nodejs-5\lib\io\packet-input-stream.js:107:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
 From event:
    at C:\projects\mariadb\mariadb-connector-nodejs-5\lib\connection.js:162:29
    at new Promise (<anonymous>)
    at Connection.query (C:\projects\mariadb\mariadb-connector-nodejs-5\lib\connection.js:160:12)
    at Context.<anonymous> (C:\projects\mariadb\mariadb-connector-nodejs-5\test\integration\test-error.js:386:8)
    at callFnAsync (C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runnable.js:400:21)
    at Test.Runnable.run (C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runnable.js:342:7)
    at Runner.runTest (C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runner.js:455:10)
    at C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runner.js:573:12
    at next (C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runner.js:369:14)
    at C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runner.js:379:7
    at next (C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runner.js:303:14)
    at Immediate.<anonymous> (C:\projects\mariadb\mariadb-connector-nodejs-5\node_modules\mocha\lib\runner.js:347:5)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
  fatal: false,
  errno: 1146,
  sqlState: '42S02',
  code: 'ER_NO_SUCH_TABLE' }
```
There is no debug log of query that went well, but an option can be added, problem is that sensitive information might be logged then.
