### ISSUE TITLE
Cannot pass JSON object to st_geoFromgeojson..

### ISSUE THREAD

**Issue by markddrake** [MariaDB/mariadb-connector-nodejs#21]
`This code...
`"use strict"
const mariadb = require('mariadb');

async function main() {

    const connectionDetails = {
            host      : "192.168.1.250"
           ,user      : "root"
           ,password  : "oracle"
           ,port      : 3307
           ,database  : "mysql"
           ,multipleStatements: true
    }
    
  let results;
    
  try {
    
    const pool = mariadb.createPool(connectionDetails);
    const conn = await pool.getConnection();
    results = await conn.query(`SET SESSION SQL_MODE=ANSI_QUOTES`);
    results = await conn.query(`CREATE DATABASE IF NOT EXISTS "TEST1"`);    
    results = await conn.query(`DROP TABLE IF EXISTS "TEST"`);
    results = await conn.query(`CREATE TABLE IF NOT EXISTS "TEST" ("ID" INT, "LOCN" GEOMETRY)`);
    results = await conn.query(`INSERT INTO "TEST" ("ID","LOCN") VALUES (?,ST_GeomFromGeoJSON(?))`,[1,{"type": "Point","coordinates": [28.8575834,47.0055601]}]);
   conn.end()
   pool.end();
 } catch(e) {
   console.log(e);
 }
}
main();
`

results in

`C:\Development\YADAMU\MariaDB>node client\test1
{ Error: (conn=1588, no: 4079, SQLState: HY000) Illegal parameter data type geometry for operation 'st_geomfromgeojson'
sql: INSERT INTO "TEST" ("ID","LOCN") VALUES (?,ST_GeomFromGeoJSON(?)) - parameters:[1,{"type":"Point","coordinates":[28.8575834,47.0055601]}]
    at Object.module.exports.createError (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\misc\errors.js:55:10)
    at Packet.readError (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet.js:494:19)
    at Query.readResponsePacket (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\cmd\resultset.js:47:28)
    at PacketInputStream.receivePacket (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet-input-stream.js:51:9)
    at PacketInputStream.onData (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet-input-stream.js:107:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
  fatal: false,
  errno: 4079,
  sqlState: 'HY000',
  code: 'ER_ILLEGAL_PARAMETER_DATA_TYPE_FOR_OPERATION' }`

 I can get round it by 'stringifying' the geoJSON object. but I don't think that should be necessary ?

**Comment by markddrake** [comment]
Here's a better testcase... 

BTW it also appears that the two statements that succeed result in the creation 
of 
[MariaDBGeoJson.txt](https://github.com/MariaDB/mariadb-connector-nodejs/files/2466944/MariaDBGeoJson.txt)
invalid geometry objects...

**Comment by markddrake** [comment]
Results from running the t/c

`C:\Development\YADAMU\MariaDB>node client\test1
Database Created
Table Created
Insert 1 Successful
Insert 2 Failed
{ Error: (conn=1697, no: 1416, SQLState: 22003) Cannot get geometry object from data you send to the GEOMETRY field
sql: INSERT INTO "TEST" ("ID","LOCN") VALUES (?,?) - parameters:[2,'{"type":"Point","coordinates":[28.8575834,47.0055601]}']
    at Object.module.exports.createError (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\misc\errors.js:55:10)
    at Packet.readError (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet.js:494:19)
    at Query.readResponsePacket (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\cmd\resultset.js:47:28)
    at PacketInputStream.receivePacket (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet-input-stream.js:51:9)
    at PacketInputStream.onData (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet-input-stream.js:107:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
  fatal: false,
  errno: 1416,
  sqlState: '22003',
  code: 'ER_CANT_CREATE_GEOMETRY_OBJECT' }
Insert 3 Failed
{ Error: (conn=1697, no: 4079, SQLState: HY000) Illegal parameter data type geometry for operation 'st_geomfromgeojson'
sql: INSERT INTO "TEST" ("ID","LOCN") VALUES (?,ST_GeomFromGeoJSON(?)) - parameters:[3,{"type":"Point","coordinates":[28.8575834,47.0055601]}]
    at Object.module.exports.createError (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\misc\errors.js:55:10)
    at Packet.readError (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet.js:494:19)
    at Query.readResponsePacket (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\cmd\resultset.js:47:28)
    at PacketInputStream.receivePacket (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet-input-stream.js:51:9)
    at PacketInputStream.onData (C:\Development\YADAMU\MariaDB\client\node_modules\mariadb\lib\io\packet-input-stream.js:107:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
  fatal: false,
  errno: 4079,
  sqlState: 'HY000',
  code: 'ER_ILLEGAL_PARAMETER_DATA_TYPE_FOR_OPERATION' }
Insert 4 Successfull

C:\Development\YADAMU\MariaDB>mysql -u root -poracle -Dmysql -h 192.168.1.250 -P3307
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1707
Server version: 10.3.9-MariaDB mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [mysql]> use TEST1;
Database changed
MariaDB [TEST1]> show tables;
+-----------------+
| Tables_in_test1 |
+-----------------+
| test            |
+-----------------+
1 row in set (0.001 sec)

MariaDB [TEST1]> desc test
    -> l
    -> ;
Empty set (0.010 sec)

MariaDB [TEST1]> desc test;
+-------+----------+------+-----+---------+-------+
| Field | Type     | Null | Key | Default | Extra |
+-------+----------+------+-----+---------+-------+
| ID    | int(11)  | YES  |     | NULL    |       |
| LOCN  | geometry | YES  |     | NULL    |       |
+-------+----------+------+-----+---------+-------+
2 rows in set (0.013 sec)

MariaDB [TEST1]> select * from test;
+------+---------------------------+
| ID   | LOCN                      |
+------+---------------------------+
|    1 |        ¡ù≡òè█<@╠╘1╢ÇG@ |
|    4 |        ¡ù≡òè█<@╠╘1╢ÇG@ |
+------+---------------------------+
2 rows in set (0.001 sec)

MariaDB [TEST1]>`

**Comment by markddrake** [comment]
Ok, it's not a insert issue, the problem lies with the output of the JSON_ARRAY function ( which is being ingested by the code I am working on).  

First with my comment about corrupt inserts I did not realize that unlike MYSQL the MariaDB MYSQL command line tool does not automatically output geometry in human readable form. Don't know if that's considered a bug, I don't see that the observed behavior is of much use. 

Second the MariaDB implementation of JSON_ARRAY converts a 'naked' geometry column into a series of  'escapes'. If you wrap the geometry column with a ST_asGeoJSON operator the JSON_ARRAY operator treats the output of ST_ASGeoJSON as  string, and convert the JSON Into an escaped string.. If you wrap the ST_ASGEOJSON with a JSON_QUERY(..,'$') this will sometimes cause the output to generated as JSON, and sometimes as String. From what I can tell it is dependant on the number of columns passed to the JSON_ARRAY operator, if the JSON_QUERY(ST_ASGEOJSON is the first or second argument to the JSON_ARRAY then it behaves as I would export, insert a geoJSON object. If it's the third or greater column then then it inserts a String containing an escaped representation of the GEOJSON into the output... 


My problems were causes by the fact as I was trying to re-insert the junk that JSON_ARRAY generated....

 Sorry for the distraction.
