### ISSUE TITLE
Bad Connection Pool Config Can Cause CPU Thrashing

### ISSUE THREAD

**Issue by kfitzgerald** [MariaDB/mariadb-connector-nodejs#45]
Greetings,

In my clumsiness, I specified an invalid database name in the `createPool` config. Since my app did not actually open any connections to the pool, there was visibly nothing wrong. The app functioned great.

However, when I would keep the app running, Docker would burn 150% CPU. I initially thought it was Docker's fault due to all the com.docker.hyperkit CPU issues out there, but after investigation, I realized that in [pool.js `handleConnectionError`](https://github.com/MariaDB/mariadb-connector-nodejs/blob/master/lib/pool.js#L306), it happily eats the error and retries opening connections as fast as it possibly can. 

For example, after changing `pool.js` to include a global error counter:

```js
  const handleConnectionError = function(pool, err) {
    global.errors++;
```

Then running:

```js
global.errors = 0;

const MariaDB = require('mariadb');
const pool = MariaDB.createPool({
    host: 'localhost',
    port: 3307,
    user: 'root',
    password: 'password',
    database: 'oopspoops',
    acquireTimeout: 10000,
    connectionLimit: 5,
    minDelayValidation: 500,
    connectTimeout: 10000,
    socketTimeout: 0
});

const holdOpen = setInterval(() => {
    console.log(' > Errors: %d', global.errors)
}, 1000);
```

After 10 seconds, you'll see:

```text
$ node oops.js 
 > Errors: 397
 > Errors: 785
 > Errors: 1169
 > Errors: 1548
 > Errors: 1940
 > Errors: 2323
 > Errors: 2703
 > Errors: 3090
 > Errors: 3483
 > Errors: 3860
 > Errors: 4266
...
```

The only time the operator will notice something has gone wrong is when they first try opening a connection. For example, adding to the above example:

```js
const kaboom = setTimeout(async () => {
    try {
        await pool.query('SHOW DATABASES');
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}, 5000);
```

will then output:

```text
$ node oops.js 
 > Errors: 354
 > Errors: 729
 > Errors: 1097
 > Errors: 1479
 > Errors: 1858
 { Error: (conn=101707, no: 1049, SQLState: 42000) Unknown database 'oopspoops'
     at Object.module.exports.createError (node_modules/mariadb/lib/misc/errors.js:55:10)
     at Handshake.throwError (node_modules/mariadb/lib/cmd/command.js:34:20)
     at Handshake.handshakeResult (node_modules/mariadb/lib/cmd/handshake/handshake.js:104:21)
     at PacketInputStream.receivePacket (node_modules/mariadb/lib/io/packet-input-stream.js:73:9)
     at PacketInputStream.onData (node_modules/mariadb/lib/io/packet-input-stream.js:129:20)
     at Socket.emit (events.js:189:13)
     at addChunk (_stream_readable.js:284:12)
     at readableAddChunk (_stream_readable.js:265:11)
     at Socket.Readable.push (_stream_readable.js:220:10)
     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  From event:
     at _registerHandshakeCmd (node_modules/mariadb/lib/connection.js:641:11)
     at node_modules/mariadb/lib/connection.js:56:11
     at new Promise (<anonymous>)
     at Connection.connect (node_modules/mariadb/lib/connection.js:55:16)
     at addConnectionToPoolPromise (node_modules/mariadb/lib/pool.js:331:8)
     at process._tickCallback (internal/process/next_tick.js:63:19)
   fatal: true,
   errno: 1049,
   sqlState: '42000',
   code: 'ER_BAD_DB_ERROR' }
```

I'd happily submit a PR to address this, but I'm not sure what the best course of action is. 

I feel like repeated attempts at initializing the pool should probably trigger some sort of warning or error.

Thanks,
-Kevin

**Comment by rusher** [comment]
thanks for pointing that out, pool retry on failover must be delayed, to avoid that kind of issue.

**Comment by rusher** [comment]
New release 2.0.4 solve that (part of [pool improvement](https://github.com/MariaDB/mariadb-connector-nodejs/releases/tag/2.0.4)).

When the pool fails to create a new connection, the next connection is now delayed, avoiding looping unnecessarily and using CPU. Authentication error in pool have now a better handling.
