### ISSUE TITLE
unhandledRejection, you may have forgotten to catch a Promise rejection: TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by knoxcard** [MariaDB/mariadb-connector-nodejs#72]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'includes' of undefined
    at /etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1418:22
    at Array.map (<anonymous>)
    at MariaDBQueryGenerator.escapeAttributes (/etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1396:37)
    at MariaDBQueryGenerator.selectQuery (/etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1162:28)
    at QueryInterface.select (/etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/query-interface.js:1119:27)
    at /etc/nginx/domains/indospace.io/services/node_modules/sequelize/lib/model.js:1754:34
    at tryCatcher (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/etc/nginx/domains/indospace.io/services/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)

```

**Comment by knoxcard** [comment]
false alarm...nothing to do with the driver..

**Comment by rusher** [comment]
ok, good luck to identify your issue so !

**Comment by yogithesymbian** [comment]
i have same issue :lol: and cant tracing where is the error haha 
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: 
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1655:13)
    at /var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1646:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1644:35)
    at MySQLQueryGenerator.whereQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1626:24)
    at MySQLQueryGenerator.updateQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:320:116)
    at MySQLQueryInterface.bulkUpdate (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:350:37)
    at Function.destroy (/var/www/api/node_modules/sequelize/lib/model.js:1781:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1655:13)
    at /var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1646:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1644:35)
    at MySQLQueryGenerator.whereQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1626:24)
    at MySQLQueryGenerator.updateQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:320:116)
    at MySQLQueryInterface.bulkUpdate (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:350:37)
    at Function.destroy (/var/www/api/node_modules/sequelize/lib/model.js:1781:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1655:13)
    at /var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1646:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1644:35)
    at MySQLQueryGenerator.whereQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1626:24)
    at MySQLQueryGenerator.updateQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:320:116)
    at MySQLQueryInterface.bulkUpdate (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:350:37)
    at Function.destroy (/var/www/api/node_modules/sequelize/lib/model.js:1781:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1655:13)
    at /var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1646:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1644:35)
    at MySQLQueryGenerator.whereQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1626:24)
    at MySQLQueryGenerator.updateQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:320:116)
    at MySQLQueryInterface.bulkUpdate (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:350:37)
    at Function.destroy (/var/www/api/node_modules/sequelize/lib/model.js:1781:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1655:13)
    at /var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1646:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1644:35)
    at MySQLQueryGenerator.whereQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1626:24)
    at MySQLQueryGenerator.updateQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:320:116)
    at MySQLQueryInterface.bulkUpdate (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:350:37)
    at Function.destroy (/var/www/api/node_modules/sequelize/lib/model.js:1781:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1655:13)
    at /var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1646:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1644:35)
    at MySQLQueryGenerator.whereQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1626:24)
    at MySQLQueryGenerator.updateQuery (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:320:116)
    at MySQLQueryInterface.bulkUpdate (/var/www/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:350:37)
    at Function.destroy (/var/www/api/node_modules/sequelize/lib/model.js:1781:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
