### ISSUE TITLE
ER_GET_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by serhatleventyavas** [MariaDB/mariadb-connector-nodejs#89]
Hi everyone, 
I am using Mariadb package 2.1.3 and Mariadb server 10.3.16.

here is my Mariadb create pool configuration code block.

`import mariadb from 'mariadb';
import config from '../../../config';

const pool = mariadb.createPool({
  connectionLimit : config.dbConf.connectionLimit,
  host            : config.dbConf.host,
  user            : config.dbConf.username,
  password        : config.dbConf.password,
  database        : config.dbConf.database,
  charset         : 'utf8mb4',
});
  
module.exports = pool;`

and here is my logic code block
`async function getPlaceByUUID(req, res) {
    console.log("Get Place starting...");
    let connection = null;
    
    try {
        connection = await MysqlDatabase.getConnection();
        console.log("Get Connection is completed");
        await connection.beginTransaction();
        console.log("Transaction is beginned");

        const isAdmin = req.client.is_admin || false;
        const language = req.get('Accept-Language');
        const placeUUID = req.params.uuid;
       ....
       ....
       ....
        await connection.commit();
        await connection.release();
        res.status(200).json(new ApiResponse(false, "Place is successfully fetched", placeResult.toJSON(isAdmin)));

    } catch (error) {
        console.log("Get Place catched errors...");
        console.log(error);
        if (connection) {
            await connection.rollback();
            console.log("rollback");
            await connection.release();
        }
        if (error.name === "ApiError") {
            res.status(error.status).json(new ApiResponse(true, error.message, undefined));
        } else {
            console.log(error.stack);
            res.status(500).json(new ApiResponse(true, error.message, undefined));
        }    
    }
}
`
After 10-15 requests mariadb gives me this error.

Get Place starting...
Get Place catched errors...
{ Error: retrieve connection from pool timeout
    at Object.module.exports.createError (/Users/mac/NodeJSProjects/VisitUrfa/Backend/node_modules/mariadb/lib/misc/errors.js:55:10)
    at timeoutTask (/Users/mac/NodeJSProjects/VisitUrfa/Backend/node_modules/mariadb/lib/pool-base.js:297:16)
    at Timeout.rejectAndResetTimeout [as _onTimeout] (/Users/mac/NodeJSProjects/VisitUrfa/Backend/node_modules/mariadb/lib/pool-base.js:317:5)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  fatal: false,
  errno: 45028,
  sqlState: 'HY000',
  code: 'ER_GET_CONNECTION_TIMEOUT' }
Error: retrieve connection from pool timeout
    at Object.module.exports.createError (/Users/mac/NodeJSProjects/VisitUrfa/Backend/node_modules/mariadb/lib/misc/errors.js:55:10)
    at timeoutTask (/Users/mac/NodeJSProjects/VisitUrfa/Backend/node_modules/mariadb/lib/pool-base.js:297:16)
    at Timeout.rejectAndResetTimeout [as _onTimeout] (/Users/mac/NodeJSProjects/VisitUrfa/Backend/node_modules/mariadb/lib/pool-base.js:317:5)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

Where am I making a mistake? I have never experienced such a problem in my previous projects.

**Comment by ticuss** [comment]
I am having the same problem, did you solve it ?
